module.exports = [
     `A satisfactory.`,
    `Supplies!`,
    `Nothing, it just waved.`,
    `Because if they flew over the bay, we'd call them bagels.`,
    `Eclipse it.`,
    `I'll meet you at the corner.`,
    `That belt looks good on you.`,
    `Pear-is!`,
    `Where's Pop Corn?`,
    `I don't know, but the flag is a big plus.`,
    `Sundae school.`,
    `The post office!`,
    `No, I got them all cut!`,
    `St. Nickel-less.`,
    `To the boat doc.`,
    `Stay here! I'm going on ahead.`,
    `No, I don't think they'll fit me.`,
    `Yellow!`,
    `A yolkswagen.`,
    `I didn't know it was on fire.`,
    `Take away the s.`,
    `Lettuce pray.`,
    `It didn't have the guts.`,
    `A meltdown.`,
    `A honeycomb!`,
]