module.exports = [
     `What do you call a factory that makes okay products?`,
    `What did the janitor say when he jumped out of the closet?`,
    `What did the ocean say to the beach?`,
    `Why do seagulls fly over the ocean?`,
    `How does the moon cut his hair?`,
    `What did one wall say to the other?`,
    `What did the zero say to the eight?`,
    `Where do fruits go on vacation?`,
    `What did Baby Corn say to Mama Corn?`,
    `What's the best thing about Switzerland?`,
    `Where do you learn to make a banana split?`,
    `What has more letters than the alphabet?`,
    `Dad, did you get a haircut?`,
    `What do you call a poor Santa Claus?`,
    `Where do boats go when they're sick?`,
    `What did one hat say to the other?`,
    `Dad, can you put my shoes on?`,
    `What does a lemon say when it answers the phone?`,
    `What kind of car does an egg drive?`,
    `Dad, can you put the cat out?`,
    `How do you make 7 even?`,
    `How does a taco say grace?`,
    `Why didn't the skeleton climb the mountain?`,
    `What do you call it when a snowman throws a tantrum?`,
    `What does a bee use to brush its hair?`,
]